### ISSUE TITLE
"on conflict" in insert statement is not supported

### ISSUE THREAD

**Issue by sijoonlee** [oguimbal/pgsql-ast-parser#124]
Here's failed SQL statement

INSERT INTO "mock-table" ( id, hello, env ) VALUES ( 1, 'hello', 'testing' ) ON CONFLICT (id) DO UPDATE SET hello = EXCLUDED.hello, env = EXCLUDED.env;·`

**Comment by oguimbal** [comment]
Hi !

Could you reopen with more context ? 

Like which error you get, or a full reproduction example (with associated create table statement) that wouldnt compile on [the playground](https://oguimbal.github.io/pg-mem-playground/), but which works on a real pg db

Because this IS supported. An example of `pg-mem` unit test that passes:
![image](https://user-images.githubusercontent.com/8973947/225949605-7b45b0cd-3842-4294-a115-6c984a879195.png)
