### ISSUE TITLE
Please maintain a change and release log

### ISSUE THREAD

**Issue by imaginetheheadline** [oguimbal/pgsql-ast-parser#126]
Where can I see the update of changes made in version 11, for example?

I'm trying to diagnose what went wrong when upgrading pg-mem from 2.4.5 to 2.4.6 that causes a lot of our tests to fail. I suspect v11 of the parser might have a role to play.

**Comment by oguimbal** [comment]
Hi,

I'm usually pushing minor versions when you should only expect to have fixes in the engine.
Meaning that some edge cases are supposed to have been fixed, or some functionalities to have been added.

The v11 parser was a major release because it breaks parser v10 types.
But it should have been be transparent when it comes to pg-mem... (thus the minor version)

Two possibilities here:
- Your tests were passing for the wrong reason
- Regressions have been introduced (👉 in which case, I'd be very interested to know which queries are returning results which dont match a real pg instance!)


Either way, sorry for your troubles, you're right, I'll add a changelog in further releases.

**Comment by oguimbal** [comment]
Alternatively, you can look at the commit messages, which are often explicit (they are tagged on each release)
