### ISSUE TITLE
Preceding block-comment support?

### ISSUE THREAD

**Issue by timneedham** [oguimbal/pgsql-ast-parser#51]
Hi,

_Withstanding the slight issue with nested comments (#50)..._

Not sure how feasible this might be, but it would be incredibly useful (for me, at least :wink: ) to have parsed statements include any line or block comment immediately defined before it.

This would open-the-door to for all kinds of cool functionality, e.g. JSDoc-style things, simple comment-based decorators etc. ?

**Comment by oguimbal** [comment]
The concept of "before" is a bit blurry when it comes to comments locations.

For instance, given ```/* comment */ 2 + 2``` ... would you say that the comment is before the `+` binary operation ? Or before the `2` constant node ?

That's why you can use `parseWithComments()` instead of just `parse()` ... which will give you the parsed AST and a list of comments, with their location. Then, feel free to use `._location` info on nodes & comments to implement your own logic to attach the comments to specific nodes !
