### ISSUE TITLE
Parsing SQL breaks the case sensitive

### ISSUE THREAD

**Issue by linsolas** [oguimbal/pgsql-ast-parser#61]
Hello,

I'm creating this ticket that has an impact on `pg-mem`. All the details are in that ticket: https://github.com/oguimbal/pg-mem/issues/147

Long story short:

When we have a column with uppercase characters like `userID` with constraints on it, `pg-mem` tries to check the existence of the column before creating the constraint / index. For that it uses `pgsql-ast-parser.parseSql()` that returns a lowercased name of the column. And therefore, it fails to find the column.

The SQL is as follow: 

```sql
CREATE TABLE "userStats" (
    "userID" character varying(255) NOT NULL,
    CONSTRAINT "UQ_abb77da609fd701b7052a8b4531" UNIQUE ("userID"),
    CONSTRAINT "PK_abb77da609fd701b7052a8b4531" PRIMARY KEY ("userID")
);
```
On the [pg-mem-playground](https://oguimbal.github.io/pg-mem-playground/):

![image](https://user-images.githubusercontent.com/623217/131676765-1f51b5f2-4323-44c2-be87-d425171b92d8.png)

But with everything in lowercase, it works:

```sql
CREATE TABLE "userStats" (
    "userid" character varying(255) NOT NULL,
    CONSTRAINT "UQ_abb77da609fd701b7052a8b4531" UNIQUE ("userid"),
    CONSTRAINT "PK_abb77da609fd701b7052a8b4531" PRIMARY KEY ("userid")
);
```

![image](https://user-images.githubusercontent.com/623217/131676661-812b43b8-6d48-483c-a9a1-16ef670293b1.png)

I suppose that the object returned by `parseSql` should keep the case sensitivity of the column. What do you think?

**Comment by oguimbal** [comment]
Hi again :) 

Nice investigation. This is however not a problem with the parser... it was because pg-mem was re-parsing the content of indexed columns.
Like mentioned on the other issue, this problem is fixed & will be released soon.

1) Parser gives "userID" as an indexed column
2) Reparsing `userID` gives `userid` (because non-quoted identifiers are equivalent to their lower-cased counterpart, with postgres)

Closing that :)

**Comment by linsolas** [comment]
Thanks again @oguimbal. I was going to close this ticket indeed ;)
