### ISSUE TITLE
Does not support Postgres syntax of $<field>

### ISSUE THREAD

**Issue by joshstevens19** [oguimbal/pgsql-ast-parser#64]
Thanks for the great lib! just saw an issue with Postgres support

Does not support Postgres syntax of `$<field>`; aka

does not work:
```
SELECT * FROM table WHERE comment_id = $<fieldId>;
```

works: 
```
SELECT * FROM table  WHERE comment_id = $1;
```

```ts
const ast = parse('SELECT * FROM table  WHERE comment_id = $<fieldId>;');
 ```

**Comment by oguimbal** [comment]
Hi, I'm not sure this is valid pgsql.
Running `select $<fieldId>` fails with a syntax error on my side (whereas `select $1` is valid).

Where did you see this syntax ?

**Comment by joshstevens19** [comment]
this is for example if your passing a variable to it aka

```
await db.oneOrNone('SELECT * FROM table WHERE comment_id = $<fieldId>;', { fieldId: 1 });
```

works with post `pg` node

**Comment by joshstevens19** [comment]
I have wrote a workaround for now which is:

```
import { parse } from 'pgsql-ast-parser';
import { allQueries } from './src/database/register-all-queries';

let replaceParamNumber = 0;
const replacer = () => {
  replaceParamNumber++;
  return '$' + replaceParamNumber + '';
};

console.log('Checking sql scripts...');

for (let i = 0; i < allQueries.length; i++) {
  replaceParamNumber = 0;
  const query = allQueries[i].replace(/\$(.*?)\>/g, replacer);
  try {
    parse(query);
  } catch (err) {
    console.error(`${query} has an invalid syntax`);
    process.exit(1);
  }
}

console.log('Checking sql scripts is now complete they are all valid');
```

but would be nice if you didn't throw on $<objectPropertyName>

**Comment by oguimbal** [comment]
The parser only aims to support statements that are valid SQL statements.

The postgres protocol recognizes the `$1`, `$2` etc syntax (it is useful to write [prepared statements](https://www.postgresql.org/docs/current/sql-prepare.html)):

> To refer to the parameters in the prepared statement itself, use $1, $2, etc.

The fact that it works with a lib is not saying anything about its validity as an SQL statement (the lib you're using might do something similar to what you wrote in your previous message).

I think that this syntax is not actual SQL (it might be supported by your lib, but maybe not by another one - meaning that implementing that in a generic parser would be a mistake for those not using the same lib as you).

ps: Is your lib [node-postgres](https://www.npmjs.com/package/pg)  ? Because I cant find any mention of named query parameters in their documentation.


Reopen the issue if you find a mention somewhere in the postgres documentation about this syntax. I could not :/

**Comment by joshstevens19** [comment]
hey yes think your right here this is supported in pg-promises https://github.com/vitaly-t/pg-promise#named-parameters but as you said its not native so adding it does not make sense thanks for that message back. My script will do and still does the outcome we want thanks again for the amazing lib!

**Comment by oguimbal** [comment]
My pleasure :) Thanks for the kind words
