### ISSUE TITLE
Add support to `CREATE OR REPLACE FUNCTION`

### ISSUE THREAD

**Issue by RodolfoSilva** [oguimbal/pgsql-ast-parser#7]
Right now I can't run migrations using `pg-mem` because the AST to execute `CREATE OR REPLACE FUNCTION` is not implemented yet. 

https://www.postgresql.org/docs/9.1/sql-createfunction.html

@oguimbal is in you schedule implemente this feature, or PR's are welcome?

**Comment by oguimbal** [comment]
The problem with the "create function" statement is that the whole PL/pgSQL syntax must be implemented in order to support it (not only the query language syntax).

For this, yes, PRs are welcome, but beware, that's very far from being an easy task  :)   (and it must be discussed)

That said, something intermediate could be more easily done:  Supporting the "create function" statement, without actually parsing/compiling the function body (which would force you to declare mocks for your created pg functions directly in JS).

I've been thinking about doing that for a while... would it be something that works for you ? (i'm not sure of the relevance of this approach)

FYI, this subject [has been mentioned here](https://github.com/oguimbal/pg-mem/discussions/41?converting=1#discussioncomment-291500)

**Comment by oguimbal** [comment]
nb: I created a tracking issue about this in pg-mem https://github.com/oguimbal/pg-mem/issues/42 to avoid duplicates, so I'm closing this 

(but you can reply here, though)

**Comment by RodolfoSilva** [comment]
> For this, yes, PRs are welcome, but beware, that's very far from being an easy task :) (and it must be discussed)

I see, this should take several days to be done.

> I've been thinking about doing that for a while... would it be something that works for you ? (i'm not sure of the relevance of this approach)

@oguimbal Yes, will work! I think this approach is much better for testings.
