### ISSUE TITLE
column name order in select giving exception error 

### ISSUE THREAD

**Issue by jb-ashish** [oguimbal/pgsql-ast-parser#79]
select order, name from ts_users WHERE name = 'ash';

Error: Syntax error at line 1 col 13:

select order,
^
Unexpected comma token: ",". Instead, I was expecting to see one of the following:

**Comment by oguimbal** [comment]
expected behaviour as well 😉

![image](https://user-images.githubusercontent.com/8973947/168145732-b33035e4-6fef-492a-957a-4773781289b1.png)

 "order" is an sql keyword, you cannot use it as a name.

If you want to name a column like that, then double-quote it `select "order", name from ts_users WHERE name = 'ash'`
